id: predict-image-orientation
name: predict-image-orientation
description: This task template trains a model that will predict if an input image is rotated by 180 degrees.
is_active: true
project_type: 1
param_groups:
- name: inputs
  params:
  - name: dataset
    description: Dataset with images.
    value: null
    data_type: dataset
    required: true
- name: outputs
  params:
  - name: orientationModel
    description: Trained orientation classifier.
    value: null
    data_type: dataset
    required: false
- name: parameters
  params:
  - name: labelColumn
    description: Coulumn of the Coretex metadata that will be used as prediction labels for the model
    value: "Rotate"
    data_type: str
    required: true
  - name: validSplit
    description: Percentage of dataset which will be used for validation
    value: 0.2
    data_type: float
    required: true
  - name: batchSize
    description: The batch size used during taining.
    value: 32
    data_type: int
    required: true
  - name: lr
    description: Learning rate.
    value: 0.0003
    data_type: float
    required: true
  - name: epochs
    description: N/A
    value: 10
    data_type: int
    required: true
  - name: imageSize
    description: N/A
    value: 512
    data_type: int
    required: true
