id: llm-text-processing
name: "LLM: Text Processing"
description: This task template processes the contents of a text file based on an instruction (e.g. summarize) using an LLM through Ollama
is_active: true
project_type: 8
param_groups:
- name: inputs
  params:
  - name: dataset
    description: Dataset containing a single .txt file with the text to be processed
    value: null
    data_type: dataset
    required: true
- name: parameters
  params:
  - name: prompt
    description: Prompt that will be used to instruct the model on what to do with the text
    value: null
    data_type: str
    required: true
  - name: model
    description: Ollama model that will be used to perform the processing (avilable models can be found at https://ollama.com/library)
    value: llama2
    data_type: str
    required: false
