id: stable-diffusion
name: Stable Diffusion
description: This task template runs Stable Diffusion text-to-image.
is_active: true
project_type: 1
param_groups:
  - name: inputs
    params:
      - name: prompts
        description: Input prompt for Stable Diffusion.
        value:
          - a professional photograph of an astronaut riding a horse
        data_type: list[str]
        required: true
      - name: negativePrompt
        description: Negative prompt for Stable Diffusion.
        value: null
        data_type: str
        required: false
  - name: outputs
    params:
      - name: generatedDataset
        description: Generated image dataset.
        value: null
        data_type: dataset
        required: false
  - name: parameters
    params:
      - name: height
        description: Height of the generated image.
        value: 768
        data_type: int
        required: true
      - name: width
        description: Width of the generated image.
        value: 768
        data_type: int
        required: true
      - name: steps
        description: Number of Stable Diffusion steps.
        value: 50
        data_type: int
        required: true
      - name: imageCount
        description: Number of generated images per prompt.
        value: 1
        data_type: int
        required: true
      - name: seed
        description: Set seed for reproducibility of generated images.
        value: null
        data_type: int
        required: false
