id: image-annotation-extractor
name: Image Annotation Extractor
description: Extracts rectangular annotations of the image as separate images
is_active: true
project_type: 1
param_groups:
- name: inputs
  params:
  - name: dataset
    description: Dataset containing the annotations which will be used for synthetically
      generating more data
    value: null
    data_type: dataset
    required: true
- name: outputs
  params:
  - name: outputDataset
    description: Dataset which is generated as a result of executing this Task
    value: null
    data_type: dataset
    required: false
- name: parameters
  params:
  - name: parentClass
    description: Annotated regions from other classes will be perspective transformed based on this one,
      and extracted to a separate image.
    value: null
    data_type: str
    required: false
  - name: excludedClasses
    description: Annotation classes that will not be extracted
    value: null
    data_type: list[str]
    required: false
