id: ollama-rag-index
name: Rag index
description: Geneates a dataset with paragraphs and their index from PDF and txt files whih will be used in RAG-endpoint
is_active: true
project_type: 8
param_groups:
- name: inputs
  params:
  - name: dataset
    description: Dataset containing PDF and txt files which will act as external data for enriched responses through RAG
    value: null
    data_type: dataset
    required: true
- name: outputs
  params:
  - name: outputDataset
    description: Dataset with paragraphs and their index from PDF and txt files whih will be used in RAG-endpoint
    value: null
    data_type: dataset
    required: false
