id: synthetic-image-generator
name: Synthetic Image Generator
description: This task stitches images onto background images in random locations,
  while applying rotation and scaling.
is_active: true
project_type: 1
param_groups:
- name: inputs
  params:
  - name: dataset
    description: Dataset with images which will be stitched onto background images.
    value: null
    data_type: dataset
    required: true
  - name: backgroundDataset
    description: Dataset containing background images on which the annotations from
      the "dataset" parameter will be stiched on
    value: null
    data_type: dataset
    required: true
- name: outputs
  params:
  - name: outputDataset
    description: Dataset which is generated as a result of executing this Task
    value: null
    data_type: dataset
    required: false
- name: parameters
  params:
  - name: augmentationsPerImage
    description: How many augnmented images will be generated per input image.
    value: 5
    data_type: int
    required: true
  - name: seed
    description: Seed parameter. Added for reproducibility
    value: 42
    data_type: int
    required: true
  - name: minImageSize
    description: Minimum image size compared to background image
    value: 0.2
    data_type: float
    required: true
  - name: maxImageSize
    description: Maximum image size compared to background image
    value: 0.8
    data_type: float
    required: true
  - name: maxRotationAngle
    description: Maximum rotation angle which will be applied to image
      before stiching it to a background
    value: 3
    data_type: float
    required: true
  - name: excludedClasses
    description: These classes will be ignored.
    value: null
    data_type: list[str]
    required: false
